version: "3.8"

services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:secret@mongo:27017/mydatabase?authSource=admin"
    volumes:
      - /src
      - /node_modules

  mongo:
    image: "mongo:6.0"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  mongo-data:
